[package]
name = "raster"
version = "0.0.6"
license = "MIT"
authors = ["kosinix <kosinix@users.noreply.github.com>"]
exclude = [
    "main.rs",
    "dev/*",
    "tests/*",
]
keywords = [
    "image", "image-processing"
]
readme = "README.md"
description = "Image processing lib for Rust"
documentation = "https://kosinix.github.io/raster/raster/"
homepage = "https://github.com/kosinix/raster"
repository = "https://github.com/kosinix/raster.git"

[dependencies.image]
version = "0.10.3"
default-features = false
features = ["gif_codec", "jpeg", "ico", "png_codec"]